"""Parameter recovery tests for all choice models.

Tests that each model can recover its true parameters from synthetic data
generated by the corresponding DGP function.  These tests verify that the
estimation machinery works end-to-end and that recovered coefficients are
within a reasonable tolerance of the ground truth.

Each DGP uses 10,000 observations and includes chooser×alternative
interaction terms for better parameter identification.  Tolerances are
set generously (rtol=0.20 for betas, rtol=0.30 for structural parameters)
because MLE estimates have sampling variability.
"""

import numpy.testing as npt
import pytest

from locpick import MultinomialLogit
from locpick.dgp import (
    simulate_mixed_logit,
    simulate_mnl,
    simulate_mscl,
    simulate_nested_logit,
    simulate_scl,
)
from locpick.models.mixed import MixedLogit, ParamDistribution
from locpick.models.mscl import MixedSpatiallyCorrelatedLogit
from locpick.models.nested import NestedLogit
from locpick.models.scl import SpatiallyCorrelatedLogit


# ---------------------------------------------------------------------------
# MNL parameter recovery
# ---------------------------------------------------------------------------


class TestMNLRecovery:
    """Parameter recovery tests for the MNL model."""

    def test_mnl_recovers_alt_and_interaction_params(self):
        """MNL should recover both alternative-level and interaction parameters."""
        dataset = simulate_mnl(n_obs=10000, n_alts=6, seed=2026)
        model = MultinomialLogit(dataset.choice_table, "alt_feature + obs_x_alt - 1")
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["alt_feature"],
            dataset.true_params["alt_feature"],
            rtol=0.10,
        )
        npt.assert_allclose(
            result.coefficients["obs_x_alt"],
            dataset.true_params["obs_x_alt"],
            rtol=0.10,
        )

    def test_mnl_recovers_alt_only_params(self):
        """MNL should recover alternative-level parameters without interactions."""
        dataset = simulate_mnl(
            n_obs=10000,
            n_alts=5,
            alt_params={"alt_feature": -0.8},
            interaction_params={},
            seed=42,
        )
        model = MultinomialLogit(dataset.choice_table, "alt_feature - 1")
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["alt_feature"],
            dataset.true_params["alt_feature"],
            rtol=0.10,
        )


# ---------------------------------------------------------------------------
# Nested logit parameter recovery
# ---------------------------------------------------------------------------


class TestNestedLogitRecovery:
    """Parameter recovery tests for the nested logit model."""

    def test_nested_logit_recovers_beta_params(self):
        """Nested logit should recover beta coefficients within tolerance."""
        dataset = simulate_nested_logit(n_obs=10000, n_alts=4, seed=2026)
        model = NestedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost + income_x_time - 1",
            nests=dataset.nests,
        )
        result = model.fit()

        for param_name in ["cost", "time"]:
            true_val = dataset.true_params[param_name]
            npt.assert_allclose(
                result.coefficients[param_name],
                true_val,
                rtol=0.30,
                err_msg=f"Nested logit failed to recover {param_name}",
            )

    def test_nested_logit_recovers_lambda_params(self):
        """Nested logit should recover nest dissimilarity parameters."""
        dataset = simulate_nested_logit(n_obs=10000, n_alts=4, seed=2026)
        model = NestedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost + income_x_time - 1",
            nests=dataset.nests,
        )
        result = model.fit()

        for nest_name, true_lambda in dataset.true_lambdas.items():
            est_lambda = result.coefficients[f"lambda_{nest_name}"]
            npt.assert_allclose(
                est_lambda,
                true_lambda,
                rtol=0.30,
                err_msg=f"Nested logit failed to recover lambda_{nest_name}",
            )

    def test_nested_logit_mnl_data_lambda_near_one(self):
        """When data is MNL (lambda≈1), estimated lambdas should be > 0."""
        dataset = simulate_nested_logit(
            n_obs=10000,
            n_alts=4,
            nest_lambdas={"transit": 0.99, "auto": 0.99},
            seed=42,
        )
        model = NestedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost + income_x_time - 1",
            nests=dataset.nests,
        )
        result = model.fit()

        for nest_name in dataset.true_lambdas:
            est_lambda = result.coefficients[f"lambda_{nest_name}"]
            assert est_lambda > 0.0, f"lambda_{nest_name} should be > 0, got {est_lambda:.3f}"


# ---------------------------------------------------------------------------
# SCL parameter recovery
# ---------------------------------------------------------------------------


class TestSCLRecovery:
    """Parameter recovery tests for the SCL model."""

    def test_scl_recovers_beta_params(self):
        """SCL should recover beta coefficients within tolerance."""
        dataset = simulate_scl(n_obs=3000, n_alts=6, rho=0.7, seed=2026)
        model = SpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
        )
        result = model.fit()

        for param_name in ["cost", "time"]:
            true_val = dataset.true_params[param_name]
            npt.assert_allclose(
                result.coefficients[param_name],
                true_val,
                rtol=0.30,
                err_msg=f"SCL failed to recover {param_name}",
            )

    def test_scl_recovers_rho(self):
        """SCL should recover the dissimilarity parameter ρ."""
        dataset = simulate_scl(n_obs=3000, n_alts=6, rho=0.7, seed=2026)
        model = SpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
        )
        result = model.fit()

        est_rho = result.coefficients["rho"]
        npt.assert_allclose(
            est_rho,
            dataset.true_rho,
            rtol=0.40,
            err_msg="SCL failed to recover rho",
        )

    def test_scl_mnl_data_rho_near_one(self):
        """When data is MNL (rho≈1), estimated rho should be > 0."""
        dataset = simulate_scl(n_obs=3000, n_alts=6, rho=0.99, seed=42)
        model = SpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
        )
        result = model.fit()

        est_rho = result.coefficients["rho"]
        assert est_rho > 0.0, f"rho should be > 0 for MNL data, got {est_rho:.3f}"


# ---------------------------------------------------------------------------
# Mixed logit parameter recovery
# ---------------------------------------------------------------------------


class TestMixedLogitRecovery:
    """Parameter recovery tests for the mixed logit model."""

    def test_mixed_logit_recovers_fixed_params(self):
        """Mixed logit should recover fixed coefficients within tolerance."""
        dataset = simulate_mixed_logit(n_obs=5000, n_alts=4, seed=2026)
        model = MixedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            random_params={
                "time": ParamDistribution("normal", "time"),
            },
            n_draws=150,
            draw_type="halton",
            seed=42,
        )
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["cost"],
            dataset.true_params["cost"],
            rtol=0.30,
            err_msg="Mixed logit failed to recover fixed param 'cost'",
        )

    def test_mixed_logit_recovers_random_param_means(self):
        """Mixed logit should recover random coefficient means."""
        dataset = simulate_mixed_logit(n_obs=5000, n_alts=4, seed=2026)
        model = MixedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            random_params={
                "time": ParamDistribution("normal", "time"),
            },
            n_draws=150,
            draw_type="halton",
            seed=42,
        )
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["mean_time"],
            dataset.true_params["mean_time"],
            rtol=0.40,
            err_msg="Mixed logit failed to recover mean_time",
        )

    def test_mixed_logit_zero_spread_reduces_to_mnl(self):
        """When all spreads are zero, mixed logit should recover MNL params."""
        dataset = simulate_mnl(n_obs=10000, n_alts=4, seed=42)
        model = MultinomialLogit(dataset.choice_table, "alt_feature + obs_x_alt - 1")
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["alt_feature"],
            dataset.true_params["alt_feature"],
            rtol=0.10,
        )


# ---------------------------------------------------------------------------
# MSCL parameter recovery
# ---------------------------------------------------------------------------


class TestMSCLRecovery:
    """Parameter recovery tests for the MSCL model."""

    def test_mscl_recovers_fixed_params(self):
        """MSCL should recover fixed coefficients within tolerance."""
        dataset = simulate_mscl(n_obs=3000, n_alts=6, rho=0.7, seed=2026)
        model = MixedSpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
            random_params={
                "time": ParamDistribution("normal", "time"),
            },
            n_draws=100,
        )
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["cost"],
            dataset.true_params["cost"],
            rtol=0.30,
            err_msg="MSCL failed to recover fixed param 'cost'",
        )

    def test_mscl_recovers_rho(self):
        """MSCL should recover the dissimilarity parameter ρ."""
        dataset = simulate_mscl(n_obs=3000, n_alts=6, rho=0.7, seed=2026)
        model = MixedSpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
            random_params={
                "time": ParamDistribution("normal", "time"),
            },
            n_draws=100,
        )
        result = model.fit()

        est_rho = result.coefficients["rho"]
        # Rho recovery in MSCL is harder; use wider tolerance
        npt.assert_allclose(
            est_rho,
            dataset.true_rho,
            rtol=0.50,
            err_msg="MSCL failed to recover rho",
        )

    def test_mscl_no_random_params_recovers_scl(self):
        """MSCL with no random params should behave like SCL."""
        dataset = simulate_scl(n_obs=3000, n_alts=6, rho=0.7, seed=42)
        model = MixedSpatiallyCorrelatedLogit(
            dataset.choice_table,
            formula="cost + time + income_x_cost - 1",
            graph=dataset.adjacency,
            random_params={},
            n_draws=50,
        )
        result = model.fit()

        # Should recover beta params
        for param_name in ["cost", "time"]:
            true_val = dataset.true_params[param_name]
            npt.assert_allclose(
                result.coefficients[param_name],
                true_val,
                rtol=0.30,
                err_msg=f"MSCL (no random) failed to recover {param_name}",
            )
