"""Parameter recovery tests for the SAR-MNL model (PML estimator).

Tests that the SARMNL model can recover its true parameters from
synthetic data generated by ``simulate_sar_mnl``.  These tests verify
that the PML estimation machinery works end-to-end and that recovered
coefficients are within a reasonable tolerance of the ground truth.

Tolerances follow the existing ``test_param_recovery.py`` conventions:
- β coefficients: rtol=0.20 (generous, accounts for PML efficiency loss)
- ρ (spatial parameter): rtol=0.30 for moderate ρ; rtol=0.50 for low ρ
- ρ=0 equivalence with MNL: rtol=1e-4 (should be nearly exact)
"""

import numpy as np
import numpy.testing as npt

from locpick import ChoiceModel
from locpick.dgp import simulate_sar_mnl


class TestSARMNLRecovery:
    """Parameter recovery tests for the SAR-MNL model (PML estimator)."""

    def test_sar_mnl_recovers_beta_params(self):
        """SAR-MNL should recover beta coefficients within tolerance."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.3, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        result = model.fit()

        for param_name in ["alt_attr", "obs_x_alt"]:
            true_val = dataset.true_params[param_name]
            npt.assert_allclose(
                result.coefficients[param_name],
                true_val,
                rtol=0.20,
                err_msg=f"SAR-MNL failed to recover {param_name}",
            )

    def test_sar_mnl_recovers_rho(self):
        """SAR-MNL should recover the spatial autoregressive parameter ρ."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.3, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        result = model.fit()

        est_rho = result.coefficients["rho"]
        npt.assert_allclose(
            est_rho,
            dataset.true_rho,
            rtol=0.30,
            err_msg="SAR-MNL failed to recover rho",
        )

    def test_sar_mnl_rho_zero_recovers_mnl(self):
        """When ρ=0, SAR-MNL should recover standard MNL estimates."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.0, seed=42)
        # Fit SAR-MNL
        sar_model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        sar_result = sar_model.fit()
        # Fit standard MNL (via ChoiceModel without W)
        mnl_model = ChoiceModel(dataset.choice_table, formula="alt_attr + obs_x_alt - 1")
        mnl_result = mnl_model.fit()

        for param_name in ["alt_attr", "obs_x_alt"]:
            npt.assert_allclose(
                sar_result.coefficients[param_name],
                mnl_result.coefficients[param_name],
                rtol=0.02,
                err_msg=f"SAR-MNL(ρ=0) != MNL for {param_name}",
            )
        # ρ should be close to 0 (within sampling variability)
        assert abs(sar_result.coefficients["rho"]) < 0.15

    def test_sar_mnl_recovers_rho_low_spatial_dep(self):
        """SAR-MNL should detect low spatial dependence (ρ=0.05) is near zero."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.05, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        result = model.fit()
        # Low ρ is hard to distinguish from zero — check it's not wildly off
        est_rho = result.coefficients["rho"]
        assert abs(est_rho) < 0.15, f"rho should be near 0, got {est_rho:.4f}"

    def test_sar_mnl_recovers_rho_moderate_spatial_dep(self):
        """SAR-MNL should recover ρ at moderate spatial dependence (ρ=0.5)."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.5, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        result = model.fit()
        npt.assert_allclose(
            result.coefficients["rho"],
            dataset.true_rho,
            rtol=0.30,
            err_msg="SAR-MNL failed to recover moderate rho",
        )

    def test_sar_mnl_smaller_n_alts(self):
        """SAR-MNL should work with a small number of alternatives."""
        dataset = simulate_sar_mnl(n_obs=3000, n_alts=12, rho=0.2, n_neighbors=3, seed=42)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        result = model.fit()
        # Should converge and produce finite estimates
        assert np.isfinite(result.coefficients["rho"])
        assert np.isfinite(result.coefficients["alt_attr"])

    def test_sar_mnl_w_input_types(self):
        """Graph, scipy.sparse, and dense W produce identical results."""
        import scipy.sparse as sp

        dataset = simulate_sar_mnl(n_obs=3000, n_alts=20, rho=0.2, seed=42)
        W_graph = dataset.W  # libpysal.graph.Graph
        W_sparse = sp.csr_array(W_graph.sparse)  # scipy.sparse
        W_dense = W_sparse.toarray()  # dense numpy

        model1 = ChoiceModel(
            dataset.choice_table,
            "alt_attr + obs_x_alt - 1",
            graph=W_graph,
            lag=True,
        )
        result1 = model1.fit()
        model2 = ChoiceModel(
            dataset.choice_table,
            "alt_attr + obs_x_alt - 1",
            graph=W_sparse,
            lag=True,
        )
        result2 = model2.fit()
        model3 = ChoiceModel(
            dataset.choice_table,
            "alt_attr + obs_x_alt - 1",
            graph=W_dense,
            lag=True,
        )
        result3 = model3.fit()

        npt.assert_allclose(
            result1.coefficients.values,
            result2.coefficients.values,
            rtol=1e-6,
            err_msg="Graph vs sparse W give different results",
        )
        npt.assert_allclose(
            result1.coefficients.values,
            result3.coefficients.values,
            rtol=1e-6,
            err_msg="Graph vs dense W give different results",
        )

    def test_sar_mnl_probabilities_sum_to_one(self):
        """Choice probabilities should sum to 1 across alternatives."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        model.fit()
        probs = model.probabilities()
        npt.assert_allclose(
            probs.sum(axis=1),
            1.0,
            atol=1e-10,
            err_msg="Probabilities do not sum to 1",
        )

    def test_sar_mnl_marginal_effects_structure(self):
        """Marginal effects: direct + indirect = total; indirect > 0 when ρ > 0."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.3, seed=42)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
        )
        model.fit()
        me = model.marginal_effects(variable="alt_attr")

        # direct + indirect = total
        npt.assert_allclose(
            me["direct"].values + me["indirect"].values,
            me["total"].values,
            rtol=1e-10,
            err_msg="direct + indirect != total",
        )

    def test_sar_mnl_gmm_recovers_rho(self):
        """Linearized GMM should recover ρ at moderate spatial dependence."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.3, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            estimator="linearized_gmm",
        )
        result = model.fit()

        # GMM is less precise — use wider tolerance
        est_rho = result.coefficients["rho"]
        assert abs(est_rho - dataset.true_rho) < 0.2, (
            f"GMM failed to recover rho: got {est_rho:.4f}, true {dataset.true_rho}"
        )

    def test_sar_mnl_cg_matches_dense(self):
        """CG path should give similar results to dense path."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)

        model_dense = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            estimator="pml",
        )
        result_dense = model_dense.fit()

        model_cg = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            estimator="pml_cg",
        )
        result_cg = model_cg.fit()

        # CG and dense should agree closely
        npt.assert_allclose(
            result_dense.coefficients.values,
            result_cg.coefficients.values,
            rtol=0.05,
            err_msg="CG and dense paths give different results",
        )


# ---------------------------------------------------------------------------
# GMM warm-start tests
# ---------------------------------------------------------------------------


class TestSARMNLWarmstart:
    """Tests for GMM warm-start of PML optimization."""

    def test_sar_mnl_warmstart_recovers_rho(self):
        """PML with warm-start should recover ρ."""
        dataset = simulate_sar_mnl(n_obs=5000, n_alts=50, rho=0.3, seed=2026)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            warmstart=True,
        )
        result = model.fit()

        npt.assert_allclose(
            result.coefficients["rho"],
            dataset.true_rho,
            rtol=0.30,
            err_msg="Warm-start PML failed to recover rho",
        )

    def test_sar_mnl_warmstart_disabled(self):
        """PML without warm-start should still work (starts from zeros)."""
        dataset = simulate_sar_mnl(n_obs=2000, n_alts=20, rho=0.2, seed=42)
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            warmstart=False,
        )
        result = model.fit()

        assert np.isfinite(result.coefficients["rho"])
        npt.assert_allclose(
            result.coefficients["rho"],
            dataset.true_rho,
            rtol=0.50,
            err_msg="No-warmstart PML failed to recover rho",
        )


# ---------------------------------------------------------------------------
# SAR-Nested, SAR-Mixed, SAR-Mixed-Nested tests
# ---------------------------------------------------------------------------


class TestSARNested:
    """Tests for SAR + Nested logit."""

    def test_sar_nested_fits_and_recovers_rho(self):
        """SAR-Nested should fit and recover ρ."""
        dataset = simulate_sar_mnl(n_obs=2000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.nested import NestingTree, NestSpec

        nest_tree = NestingTree(
            nests=[
                NestSpec(name="a", alt_ids=list(range(0, 10))),
                NestSpec(name="b", alt_ids=list(range(10, 20))),
            ]
        )
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            nests=nest_tree,
        )
        result = model.fit()

        assert np.isfinite(result.coefficients["rho"])
        npt.assert_allclose(
            result.coefficients["rho"],
            dataset.true_rho,
            rtol=0.50,
            err_msg="SAR-Nested failed to recover rho",
        )

    def test_sar_nested_rho_zero_matches_nested(self):
        """SAR-Nested with ρ≈0 should match plain nested logit."""
        dataset = simulate_sar_mnl(n_obs=2000, n_alts=20, rho=0.0, seed=42)
        from locpick.models.nested import NestingTree, NestSpec

        nest_tree = NestingTree(
            nests=[
                NestSpec(name="a", alt_ids=list(range(0, 10))),
                NestSpec(name="b", alt_ids=list(range(10, 20))),
            ]
        )
        sar_model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            nests=nest_tree,
        )
        sar_result = sar_model.fit()

        nested_model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            nests=nest_tree,
        )
        nested_result = nested_model.fit()

        for param in ["alt_attr", "obs_x_alt"]:
            npt.assert_allclose(
                sar_result.coefficients[param],
                nested_result.coefficients[param],
                rtol=0.05,
                err_msg=f"SAR-Nested(ρ=0) != Nested for {param}",
            )

    def test_sar_nested_robust_ses_finite(self):
        """SAR-Nested robust SEs should be finite."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.nested import NestingTree, NestSpec

        nest_tree = NestingTree(
            nests=[
                NestSpec(name="a", alt_ids=list(range(0, 10))),
                NestSpec(name="b", alt_ids=list(range(10, 20))),
            ]
        )
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            nests=nest_tree,
        )
        model.fit()
        cov = model.covariance_robust()
        ses = np.sqrt(np.diag(cov))
        assert np.all(np.isfinite(ses)), f"SAR-Nested robust SEs not finite: {ses}"


class TestSARMixed:
    """Tests for SAR + Mixed logit."""

    def test_sar_mixed_fits_and_recovers_rho(self):
        """SAR-Mixed should fit and recover ρ."""
        dataset = simulate_sar_mnl(n_obs=2000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.mixed import ParamDistribution

        random_params = {"obs_x_alt": ParamDistribution(distribution="normal", param="obs_x_alt")}
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            random_params=random_params,
            n_draws=100,
        )
        result = model.fit()

        assert np.isfinite(result.coefficients["rho"])
        # DGP doesn't have random coefficients, so mixed logit may
        # absorb some variance — use wide tolerance
        assert abs(result.coefficients["rho"]) < 0.6, (
            f"SAR-Mixed rho too far from true: {result.coefficients['rho']:.4f}"
        )

    def test_sar_mixed_robust_ses_finite(self):
        """SAR-Mixed robust SEs should be finite."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.mixed import ParamDistribution

        random_params = {"obs_x_alt": ParamDistribution(distribution="normal", param="obs_x_alt")}
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            random_params=random_params,
            n_draws=50,
        )
        model.fit()
        cov = model.covariance_robust()
        ses = np.sqrt(np.diag(cov))
        assert np.all(np.isfinite(ses)), f"SAR-Mixed robust SEs not finite: {ses}"


class TestSARMixedNested:
    """Tests for SAR + Mixed + Nested logit."""

    def test_sar_mixed_nested_fits(self):
        """SAR-Mixed-Nested should fit without errors."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.mixed import ParamDistribution
        from locpick.models.nested import NestingTree, NestSpec

        nest_tree = NestingTree(
            nests=[
                NestSpec(name="a", alt_ids=list(range(0, 10))),
                NestSpec(name="b", alt_ids=list(range(10, 20))),
            ]
        )
        random_params = {"obs_x_alt": ParamDistribution(distribution="normal", param="obs_x_alt")}
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            nests=nest_tree,
            random_params=random_params,
            n_draws=50,
        )
        result = model.fit()

        assert np.isfinite(result.coefficients["rho"])
        assert np.isfinite(result.coefficients["alt_attr"])

    def test_sar_mixed_nested_robust_ses_finite(self):
        """SAR-Mixed-Nested robust SEs should be finite."""
        dataset = simulate_sar_mnl(n_obs=1000, n_alts=20, rho=0.2, seed=42)
        from locpick.models.mixed import ParamDistribution
        from locpick.models.nested import NestingTree, NestSpec

        nest_tree = NestingTree(
            nests=[
                NestSpec(name="a", alt_ids=list(range(0, 10))),
                NestSpec(name="b", alt_ids=list(range(10, 20))),
            ]
        )
        random_params = {"obs_x_alt": ParamDistribution(distribution="normal", param="obs_x_alt")}
        model = ChoiceModel(
            dataset.choice_table,
            formula="alt_attr + obs_x_alt - 1",
            graph=dataset.W,
            lag=True,
            nests=nest_tree,
            random_params=random_params,
            n_draws=50,
        )
        model.fit()
        cov = model.covariance_robust()
        ses = np.sqrt(np.diag(cov))
        assert np.all(np.isfinite(ses)), f"SAR-Mixed-Nested robust SEs not finite: {ses}"
